/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.crudcentroeducativo.formularios;

/**
 *
 * @author pc
 */
public class jpAddMatricula extends javax.swing.JPanel {

    /**
     * Creates new form jpAddMatricula
     */
    public jpAddMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlAlumnos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlMatriculados = new javax.swing.JList<>();
        btnMatri1 = new javax.swing.JButton();
        btnMatriAll = new javax.swing.JButton();
        btnAlum1 = new javax.swing.JButton();
        btnAlumAll = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Añadir Matrícula:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 38, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lista de alumnos:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 113, -1, -1));

        jlAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        jlAlumnos.setForeground(new java.awt.Color(0, 0, 0));
        jlAlumnos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlAlumnos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 135, 130, 177));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Alumnos a Matricular:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 113, -1, -1));

        jlMatriculados.setBackground(new java.awt.Color(255, 255, 255));
        jlMatriculados.setForeground(new java.awt.Color(0, 0, 0));
        jlMatriculados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jlMatriculados);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 135, 136, 177));

        btnMatri1.setText(">");
        jPanel1.add(btnMatri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 150, 40, 30));

        btnMatriAll.setText(">>");
        jPanel1.add(btnMatriAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 50, 30));

        btnAlum1.setText("<");
        jPanel1.add(btnAlum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, 30));

        btnAlumAll.setText("<<");
        jPanel1.add(btnAlumAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 50, 30));

        btnAceptar.setText("Aceptar");
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAlum1;
    private javax.swing.JButton btnAlumAll;
    private javax.swing.JButton btnMatri1;
    private javax.swing.JButton btnMatriAll;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> jlAlumnos;
    private javax.swing.JList<String> jlMatriculados;
    // End of variables declaration//GEN-END:variables
}
